indice =["VNINDEX","HNX","UPCOM","VN100","VN30",
        "VNALLSHARE","VNCOND","VNCONS","VNDIAMOND","VNENE",
        "VNFIN","VNFINLEAD","VNFINSELECT","VNHEAL","VNIND",
        "HNX30","VNIT","VNMAT","VNMIDCAP","VNREAL",
        "VNSI","VNSMALLCAP","VNUTI","VNX50","VNXALLSHARE"]